# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Roy Abraham
title: Cloud/DevOps Engineer in training | Available October 2019
email: hire@royabraham.net
#website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  royabraham
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: royabraham
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
Multi-disciplined IT professional with a growth mindset, global outlook & community values.

Currently completing the Network Administration & Security Professional course at BCIT, an intensive program to upgrade skills in Linux, AWS, security & networking. This compliments my existing technical skills as a Windows Systems Administrator and my people skills from previous technical support & volunteer roles. Other interests include writing, travel, cooking, fitness & health. I've also lived in 7 countries & travelled to 63 more, which has given me valuable insight into understanding different cultures.

Available for new opportunities in October 2019.



# Projects Section
projects_title: Technical Projects



# Experience Section
experience_title: Related Experience


# Education Section
educaton_title: Education



# More Section
# more_title: When I'm Not On My Computer
more_content: | # this will include new lines to allow paragraphs
  Alongside my passion for technology, some of my other interests are:
   - Writing
   - Cooking
   - Travel
   - Health & Fitness

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
